name: wizmir
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+26

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.2
  permission_handler: ^10.0.0
  http:
  maps_launcher: ^2.0.1
  custom_info_window: ^1.0.1
  sliding_up_panel: ^2.0.0+1
  animations: ^2.0.5
  crypto: ^3.0.2
  intl_phone_number_input: ^0.7.1
  toast: ^0.3.0
  flutter_secure_storage: ^6.0.0
  flutter_staggered_animations: ^1.1.1
  rounded_loading_button: ^2.1.0
  wifi_scan: ^0.4.0+1
  fl_chart: ^0.55.2
  flutter_svg: ^1.1.1+1
  dropdown_button2: ^1.8.9
  video_player: ^2.4.7
  flick_video_player: ^0.5.0
  floating_action_bubble: ^1.1.4
  map_launcher: ^2.4.0
  speed_test_dart: ^1.0.4+1
  easy_localization: ^3.0.1
  image_picker: ^0.8.6
  dotted_border: ^2.0.0+3
  image_downloader: ^0.31.0
  cached_network_image: ^3.2.1
  octo_image: ^1.0.2
  particles_flutter: ^0.1.4
  animated_button: ^0.2.0
  camera: ^0.10.0+4
  heic_to_jpg: ^0.2.0
  flutter_image_compress: ^1.1.2
  flutter_speedtest: ^0.1.3+6
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.7
  flutter_launch: ^0.3.0
  at_gauges: ^1.0.1
  art_sweetalert: ^0.0.5
  logo_n_spinner: ^0.1.2+1
  responsive_framework: ^0.2.0
  flutter_custom_clippers: ^2.1.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  # cloud_firestore: ^4.3.1
  # open_whatsapp: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/mapicons/
    - assets/translations/
    - assets/map_styles/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700